### ISSUE TITLE
error: http.rb in `initialize': undefined method `empty?'

### ISSUE THREAD

**Issue by y-ich** [mkroman/wolfram-alpha#1]
Thank you for your efforts.

I encountered an error of title.
I think that line 33 in client.rb should be
      response = @http.get request_url(input).path

**Comment by y-ich** [comment]
Sorry, I gave you a wrong suggestion.
You need a string with path and query as an argument of get.
            url = request_url(input)
            response = @http.get "#{url.path}?#{url.query}"
(Though I am not sure that request_url is useful or not.)

**Comment by mkroman** [comment]
Hi, would you mind telling me which Ruby version you are using?

I think Ruby's net/http changed recently to support passing URI elements to the request helpers, however, I'm not entirely sure.

**Comment by mkroman** [comment]
Seems I was right. It's discussed in Feature [#6482](https://bugs.ruby-lang.org/issues/6482).

Thanks for creating the issue, I'll fix it soon.

**Comment by mkroman** [comment]
It should now be fixed in the latest version. I've pushed the updated gem to rubygems.org.
